### ISSUE TITLE
is ot working or half-finished?

### ISSUE THREAD

**Issue by qmannen** [Nicklas2751/killingfloor2-server#1]
i tried to get this to work but never did. did you personally get this to work?
it's building and creating all maps and gives no errors in the logsfrom what i can understand. it's just now showing up on the serverlist. but my other dockerfile on the same system is reachable

**Comment by Nicklas2751** [comment]
Yes I used it to Play with friends. I run it with k8s. Here's my config:

```yaml

apiVersion: v1
kind: Namespace
metadata:
  name: killingfloor2
---
apiVersion: v1
kind: Service
metadata:
  name: killingfloor2-udp
  namespace: killingfloor2
spec:
  type: NodePort
  selector:
    app: killingfloor2
  ports:
    - name: game
      port: 7777
      targetPort: game
      nodePort: 30777
      protocol: UDP
    - name: query
      port: 27015
      targetPort: query
      nodePort: 30016
      protocol: UDP
    - name: steam
      port: 20560
      targetPort: steam
      nodePort: 30560
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: killingfloor2-tcp
  namespace: killingfloor2
spec:
  type: LoadBalancer
  selector:
    app: killingfloor2
  ports:
    - name: webadmin
      port: 8080
      targetPort: webadmin
      protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: killingfloor2
  name: killingfloor2
  labels:
    app: killingfloor2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: killingfloor2
  template:
    metadata:
      labels:
        app: killingfloor2
    spec:
      containers:
        - name: killingfloor2
          image: nicklas2751/killingfloor2-server:latest@sha256:0373039e291f1ac6f27600bb6972b7bbd23154ee0a08a707d46a6bb492be335a
          imagePullPolicy: Always
          ports:
            - name: game
              containerPort: 7777
              protocol: UDP
            - name: query
              containerPort: 27015
              protocol: UDP
            - name: steam
              containerPort: 20560
              protocol: UDP
            - name: webadmin
              containerPort: 8080
              protocol: TCP
          env:
            - name: ADMIN
              value: "something"
            - name: ADMIN_PASSWORD
              value: "example"
            - name: ENABLE_WEBADMIN
              value: "true"
          resources:
            limits:
              cpu: "1"
              memory: "8Gi"
            requests:
              cpu: "500m"
              memory: "4Gi"
#          command: ["/bin/sh", "-c", "sleep infinity"]
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: killingfloor2-ingress
  namespace: killingfloor2

spec:
  rules:
    - host: kf2.mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: killingfloor2-tcp
              servicePort: webadmin
```

Maybe this can help you.
